using TuoiTho.Core.Policy;
using TuoiTho.Core.Time;
namespace TuoiTho.Service;
public sealed class ParentControlService(IDeviceTimePolicyStore store,ITimeUsageStore usage,IClock clock,DeviceTimePolicyEngine engine,PolicyChangeSignal changes)
{
 public ParentControlService(IDeviceTimePolicyStore store,IClock clock,PolicyChangeSignal changes) : this(store,new EmptyUsageStore(),clock,new DeviceTimePolicyEngine(clock),changes) { }
 private sealed class EmptyUsageStore : ITimeUsageStore { public Task<TimeTrackingCheckpoint?> LoadCheckpointAsync(string profileId,CancellationToken cancellationToken=default)=>Task.FromResult<TimeTrackingCheckpoint?>(null); public Task SaveAsync(string profileId,TimeTrackingCheckpoint checkpoint,IReadOnlyList<DailyUsageSlice> slices,CancellationToken cancellationToken=default)=>Task.CompletedTask; public Task<TimeSpan> GetUsageAsync(string profileId,DateOnly date,CancellationToken cancellationToken=default)=>Task.FromResult(TimeSpan.Zero); }
 public async Task<ParentControlResult> ExecuteAsync(ParentControlCommand command,string sid,IReadOnlySet<string> parents,CancellationToken token=default)
 {
  if(string.IsNullOrWhiteSpace(sid)||(!parents.Contains(sid)&&!string.Equals(sid,"S-1-5-18",StringComparison.OrdinalIgnoreCase)))return new(false,"UNAUTHORIZED");
  if(string.IsNullOrWhiteSpace(command.ProfileId)||command.ManagedSessionId<0)return new(false,"INVALID_COMMAND");var policy=await store.LoadAsync(command.ProfileId,token);if(policy is null||policy.ManagedSessionId!=command.ManagedSessionId)return new(false,"PROFILE_OR_SESSION_MISMATCH");
  if(command.Action==ParentControlAction.GetStatus)return new(true,null,policy,await StatusAsync(policy,token));
  switch(command.Action){case ParentControlAction.GrantMinutes:if(command.Minutes is null or <=0 or >1440)return new(false,"INVALID_GRANT");await store.AddGrantAsync(policy.ProfileId,new TemporaryGrant(command.Minutes.Value,EndOfLocalDay(clock.UtcNow,clock.LocalTimeZone)),token);break;case ParentControlAction.EmergencyOverride:policy=policy with{ParentOverride=true,ParentLock=false};break;case ParentControlAction.ClearOverride:policy=policy with{ParentOverride=false};break;case ParentControlAction.SetParentLock:policy=policy with{ParentLock=true,ParentOverride=false};break;case ParentControlAction.ClearParentLock:policy=policy with{ParentLock=false};break;default:return new(false,"UNKNOWN_ACTION");}
  await store.SaveAsync(policy,token);changes.Notify();return new(true,null,policy,await StatusAsync(policy,token));
 }
 private async Task<ParentControlStatus> StatusAsync(DeviceTimePolicy policy,CancellationToken token){var local=TimeZoneInfo.ConvertTime(clock.UtcNow,clock.LocalTimeZone);var used=await usage.GetUsageAsync(policy.ProfileId,DateOnly.FromDateTime(local.DateTime),token);var grants=await store.GetGrantsAsync(policy.ProfileId,token);var active=grants.Where(g=>g.ExpiresAtUtc>clock.UtcNow).ToArray();var decision=engine.Evaluate(policy,used,active);var state=policy.ParentOverride?"OVERRIDE":decision.Allowed?"ALLOWED":PolicyReasonText.ToDisplayText(decision.Reason);return new(policy.ProfileId,policy.ManagedSessionId,policy.TestMode,(int)Math.Floor(used.TotalMinutes),policy.DailyQuotaMinutes,active.Sum(g=>g.Minutes),decision.RemainingMinutes,state);}
 private static DateTimeOffset EndOfLocalDay(DateTimeOffset utc,TimeZoneInfo zone){var local=TimeZoneInfo.ConvertTime(utc,zone);var next=local.Date.AddDays(1);return new DateTimeOffset(next,zone.GetUtcOffset(next)).ToUniversalTime();}
}