namespace TuoiTho.Core.Policy;
public enum ParentControlAction { GrantMinutes, EmergencyOverride, ClearOverride, SetParentLock, ClearParentLock, GetStatus, ResetM1, GetApps, RefreshApps, AllowApp, BlockApp, RemoveAppRule, EnableM2AppEnforcement, DisableM2AppEnforcement, EnableM2AllowlistEnforcement, DisableM2AllowlistEnforcement, BulkAllowRunningApps, GetWebRules, SaveWebRule, RemoveWebRule }
public sealed record ParentControlCommand(ParentControlAction Action,string ProfileId,int ManagedSessionId,int? Minutes=null,AppIdentity? Application=null, WebRule? WebRule=null);
public sealed record ParentActivityDiagnostics(bool SessionAgentConnected,string ActivityState,double? IdleSeconds,double? SampleAgeSeconds,int TrackedSessionId,double RecordedTodaySeconds,DateTimeOffset? LastCheckpointAtUtc,bool ExplicitLockLatched,int? WtsConnectionState,int? WtsSessionFlags,bool SessionNotificationsAvailable,string? NotificationError,int IdleThresholdMinutes,string ActivitySource="UNAVAILABLE",double? WindowsIdleSeconds=null);
public sealed record ParentObservedApp(AppIdentity Identity,AppClassification Classification,AppSimulationDecision Decision,string Reason,DateTimeOffset LastSeenUtc,AppRuleDecision? ExplicitRule=null,string? EnforcementStatus=null);
public sealed record ParentAppDiscoveryDiagnostics(DateTimeOffset? LastScanAtUtc,int ProcessesExamined,int AppsDiscovered,int AppsSkippedInaccessible,string? DiscoveryError,int UserApplications=0,int BackgroundHelpers=0,int SystemProtected=0);
public sealed record ParentAppControlStatus(DefaultAppPolicy DefaultPolicy,IReadOnlyList<ParentObservedApp> ObservedApps,ParentAppDiscoveryDiagnostics? Discovery=null,ParentAppEnforcementStatus? Enforcement=null,bool TestMode=false);
public sealed record ParentControlStatus(string ProfileId,int ManagedSessionId,bool TestMode,int UsedMinutes,int QuotaMinutes,int GrantMinutes,int RemainingMinutes,string State,ParentActivityDiagnostics? Diagnostics=null,double AllowedSeconds=0,double RemainingSeconds=0,ParentAppControlStatus? Apps=null,ParentWebControlStatus? Web=null);
/// <summary>Ephemeral browser health only; this deliberately contains no URL or browsing history.</summary>
public sealed record ParentBrowserRuntimeStatus(bool ExtensionConnected, DateTimeOffset? LastCheckedAtUtc, string LastResult, string BrowserPolicyState = "STARTING", string? BrowserPolicyError = null);
public sealed record ParentWebControlStatus(IReadOnlyList<WebRule> Rules, ParentBrowserRuntimeStatus? RuntimeStatus = null);
public sealed record ParentControlResult(bool Accepted,string? Error,DeviceTimePolicy? Policy=null,ParentControlStatus? Status=null,string? Message=null);
