using System.Text.Json;
using TuoiTho.Core.Policy;
namespace TuoiTho.Storage;
public sealed class SqliteDeviceTimePolicyStore(SqliteDatabase database) : IDeviceTimePolicyStore
{
 public async Task<DeviceTimePolicy?> LoadAsync(string profileId,CancellationToken cancellationToken=default){await using var c=await database.OpenConnectionAsync(cancellationToken);await using var q=c.CreateCommand();q.CommandText="SELECT policy_json FROM device_time_policies WHERE profile_id=$id";q.Parameters.AddWithValue("$id",profileId);var r=await q.ExecuteScalarAsync(cancellationToken);return r is null?null:JsonSerializer.Deserialize<DeviceTimePolicy>((string)r);}
 public async Task SaveAsync(DeviceTimePolicy policy,CancellationToken cancellationToken=default){await using var c=await database.OpenConnectionAsync(cancellationToken);await using var q=c.CreateCommand();q.CommandText="INSERT INTO device_time_policies(profile_id,policy_json,updated_at_utc) VALUES($id,$json,$now) ON CONFLICT(profile_id) DO UPDATE SET policy_json=excluded.policy_json,updated_at_utc=excluded.updated_at_utc";q.Parameters.AddWithValue("$id",policy.ProfileId);q.Parameters.AddWithValue("$json",JsonSerializer.Serialize(policy));q.Parameters.AddWithValue("$now",DateTimeOffset.UtcNow.ToString("O"));await q.ExecuteNonQueryAsync(cancellationToken);}
 public async Task AddGrantAsync(string profileId,TemporaryGrant grant,CancellationToken cancellationToken=default){await using var c=await database.OpenConnectionAsync(cancellationToken);await using var q=c.CreateCommand();q.CommandText="INSERT OR IGNORE INTO child_profiles(profile_id,display_name,created_at_utc) VALUES($id,$id,$now)";q.Parameters.AddWithValue("$id",profileId);q.Parameters.AddWithValue("$now",DateTimeOffset.UtcNow.ToString("O"));await q.ExecuteNonQueryAsync(cancellationToken);q.Parameters.Clear();q.CommandText="INSERT INTO temporary_grants(grant_id,profile_id,granted_minutes,expires_at_utc) VALUES($g,$id,$m,$e)";q.Parameters.AddWithValue("$g",Guid.NewGuid().ToString("N"));q.Parameters.AddWithValue("$id",profileId);q.Parameters.AddWithValue("$m",grant.Minutes);q.Parameters.AddWithValue("$e",grant.ExpiresAtUtc.ToUniversalTime().ToString("O"));await q.ExecuteNonQueryAsync(cancellationToken);}
 public async Task<IReadOnlyList<TemporaryGrant>> GetGrantsAsync(string profileId,CancellationToken cancellationToken=default){var a=new List<TemporaryGrant>();await using var c=await database.OpenConnectionAsync(cancellationToken);await using var q=c.CreateCommand();q.CommandText="SELECT granted_minutes,expires_at_utc FROM temporary_grants WHERE profile_id=$id";q.Parameters.AddWithValue("$id",profileId);await using var r=await q.ExecuteReaderAsync(cancellationToken);while(await r.ReadAsync(cancellationToken))a.Add(new(r.GetInt32(0),DateTimeOffset.Parse(r.GetString(1),System.Globalization.CultureInfo.InvariantCulture).ToUniversalTime()));return a;}
}