using System.Globalization;
using TuoiTho.Core.Policy;
namespace TuoiTho.Parent;
public sealed class AppPolicyPanel : UserControl
{
 private readonly ParentDesktopController controller; private readonly DataGridView grid=new(){Dock=DockStyle.Fill,ReadOnly=true,AllowUserToAddRows=false,AllowUserToDeleteRows=false,AutoGenerateColumns=false,SelectionMode=DataGridViewSelectionMode.FullRowSelect,MultiSelect=false,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill};
 private readonly Label empty=new(){Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleCenter,Font=new Font("Segoe UI",11),Text="Chưa phát hiện ứng dụng nào.\r\n\r\nBạn hãy mở một ứng dụng trên máy, sau đó bấm ‘Làm mới danh sách’.",Visible=false};
 private readonly Label scan=new(){AutoSize=true,Padding=new Padding(4)}; private readonly Label confirmation=new(){AutoSize=true,Padding=new Padding(4)}; private readonly Button allow=new(){Text="✓ Cho phép",Enabled=false,AutoSize=true}; private readonly Button block=new(){Text="⛔ Chặn",Enabled=false,AutoSize=true}; private readonly Button remove=new(){Text="Xóa quy tắc",Enabled=false,AutoSize=true}; private IReadOnlyList<ParentObservedApp> observed=[];
 public AppPolicyPanel(ParentDesktopController controller){this.controller=controller;Dock=DockStyle.Fill;var root=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(20),RowCount=5};root.RowStyles.Add(new RowStyle(SizeType.AutoSize));root.RowStyles.Add(new RowStyle(SizeType.AutoSize));root.RowStyles.Add(new RowStyle(SizeType.AutoSize));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));root.RowStyles.Add(new RowStyle(SizeType.AutoSize));root.Controls.Add(new Label{Text="QUẢN LÝ ỨNG DỤNG",AutoSize=true,Font=new Font("Segoe UI",16,FontStyle.Bold)},0,0);root.Controls.Add(new Label{Text="Ứng dụng chưa được phụ huynh duyệt sẽ bị chặn mặc định.",AutoSize=true,Padding=new Padding(0,4,0,12)},0,1);var actions=new FlowLayoutPanel{AutoSize=true,Dock=DockStyle.Fill};var refresh=new Button{Text="Làm mới danh sách",AutoSize=true};refresh.Click+=(_,_)=>RefreshRequested?.Invoke(this,EventArgs.Empty);allow.Click+=async(_,_)=>await ApplyAsync(ParentControlAction.AllowApp,"Đã cho phép");block.Click+=async(_,_)=>await ApplyAsync(ParentControlAction.BlockApp,"Đã chặn");remove.Click+=async(_,_)=>await ApplyAsync(ParentControlAction.RemoveAppRule,"Đã xóa quy tắc của");actions.Controls.AddRange([refresh,allow,block,remove,scan,confirmation]);root.Controls.Add(actions,0,2);var holder=new Panel{Dock=DockStyle.Fill};holder.Controls.Add(grid);holder.Controls.Add(empty);root.Controls.Add(holder,0,3);Controls.Add(root);AddColumn("Ứng dụng","Name");AddColumn("Tệp chạy","Path");AddColumn("Quy tắc","Rule");AddColumn("Kết quả mô phỏng","Simulation");AddColumn("Lần thấy gần nhất","Seen");grid.SelectionChanged+=(_,_)=>SetButtons();}
 public event EventHandler? RefreshRequested;
 public static string RuleText(ParentObservedApp app)=>app.Reason switch{"EXPLICIT_ALLOW"=>"CHO PHÉP","EXPLICIT_BLOCK"=>"CHẶN",_=>"CHƯA DUYỆT"};
 public static string SimulationText(AppSimulationDecision decision)=>decision switch{AppSimulationDecision.WouldAllow=>"ĐƯỢC PHÉP",AppSimulationDecision.WouldBlock=>"SẼ BỊ CHẶN",_=>"CHƯA DUYỆT — SẼ BỊ CHẶN"};
 public static string EmptyStateText=>"Chưa phát hiện ứng dụng nào.\r\n\r\nBạn hãy mở một ứng dụng trên máy, sau đó bấm ‘Làm mới danh sách’.";
 public bool ActionsEnabled=>allow.Enabled&&block.Enabled&&remove.Enabled;
 public void SelectRow(int index){if(index<0||index>=grid.Rows.Count){grid.ClearSelection();SetButtons();return;}grid.ClearSelection();grid.Rows[index].Selected=true;grid.CurrentCell=grid.Rows[index].Cells[0];SetButtons();}
 public void Update(ParentAppControlStatus? status){var selected=Selected()?.Identity.NormalizedExecutablePath;observed=status?.ObservedApps??[];grid.Rows.Clear();foreach(var app in observed)grid.Rows.Add(app.Identity.DisplayName??app.Identity.FileName,app.Identity.NormalizedExecutablePath,RuleText(app),SimulationText(app.Decision),app.LastSeenUtc.ToLocalTime().ToString("HH:mm:ss",CultureInfo.CurrentCulture));empty.Text=status?.Discovery?.DiscoveryError is { Length: > 0 } ? "Không thể quét ứng dụng. Xem Chẩn đoán M1." : observed.Count==0 ? "Không tìm thấy ứng dụng người dùng trong phiên này." : EmptyStateText;empty.Visible=observed.Count==0;scan.Text=status?.Discovery is { } d ? $"Đã quét: {d.ProcessesExamined} process; phát hiện: {d.AppsDiscovered}; bỏ qua: {d.AppsSkippedInaccessible}" : "";grid.ClearSelection();grid.CurrentCell=null;if(selected is not null)foreach(DataGridViewRow row in grid.Rows)if(string.Equals((string?)row.Cells["Path"].Value,selected,StringComparison.OrdinalIgnoreCase)){row.Selected=true;grid.CurrentCell=row.Cells[0];break;}SetButtons();}
 private void AddColumn(string header,string name)=>grid.Columns.Add(new DataGridViewTextBoxColumn{HeaderText=header,Name=name,DataPropertyName=name});
 private ParentObservedApp? Selected()=>grid.SelectedRows.Count==1&&grid.SelectedRows[0].Index is var i&&i>=0&&i<observed.Count?observed[i]:null;
 private void SetButtons(){var has=Selected() is not null;allow.Enabled=block.Enabled=remove.Enabled=has;}
 private async Task ApplyAsync(ParentControlAction action,string verb){var app=Selected();if(app is null)return;var result=await controller.SendAppAsync(action,app.Identity);confirmation.Text=result.Success?$"{verb} {app.Identity.DisplayName??app.Identity.FileName}." : result.Message;confirmation.ForeColor=result.Success?Color.DarkGreen:Color.Firebrick;Update(result.Status?.Apps);}
}