using System.Globalization;
using TuoiTho.Core.Policy;
namespace TuoiTho.Parent;
public sealed class ParentControlForm : Form
{
 private readonly ParentDesktopController controller; private readonly System.Windows.Forms.Timer refreshTimer=new(){Interval=1000}; private readonly Dictionary<string,Label> overview=[]; private readonly Dictionary<string,Label> diagnostics=[]; private readonly Label message=new(){AutoSize=true,Font=new Font("Segoe UI",10,FontStyle.Bold),Padding=new Padding(8)}; private readonly Label countdown=new(){AutoSize=true,Text="00:00:00",Font=new Font("Segoe UI",32,FontStyle.Bold),ForeColor=Color.DarkBlue,Padding=new Padding(4)}; private Button? reset; private bool refreshing; private AppPolicyPanel? apps;
 public ParentControlForm(ParentDesktopController controller){this.controller=controller;Text="Tuổi Thơ – Điều khiển phụ huynh";StartPosition=FormStartPosition.CenterScreen;MinimumSize=new Size(1040,700);Size=new Size(1120,760);Font=new Font("Segoe UI",10);var tabs=new TabControl{Dock=DockStyle.Fill};tabs.TabPages.Add(OverviewTab());tabs.TabPages.Add(AppTab());tabs.TabPages.Add(DiagnosticsTab());Controls.Add(tabs);var status=new StatusStrip();status.Items.Add(new ToolStripControlHost(message));Controls.Add(status);refreshTimer.Tick+=async(_,_)=>await RefreshAsync();Shown+=async(_,_)=>{await RefreshAsync();refreshTimer.Start();};FormClosed+=(_,_)=>{refreshTimer.Stop();refreshTimer.Dispose();};}
 private TabPage OverviewTab(){var tab=new TabPage("TỔNG QUAN");var root=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(28),ColumnCount=2};root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));root.RowStyles.Add(new RowStyle(SizeType.AutoSize));root.RowStyles.Add(new RowStyle(SizeType.AutoSize));root.RowStyles.Add(new RowStyle(SizeType.AutoSize));var title=new Label{Text="TUỔI THƠ",Font=new Font("Segoe UI",20,FontStyle.Bold),AutoSize=true};root.Controls.Add(title,0,0);root.SetColumnSpan(title,2);var subtitle=new Label{Text="Quản lý thời gian sử dụng",AutoSize=true,Padding=new Padding(0,0,0,16)};root.Controls.Add(subtitle,0,1);root.SetColumnSpan(subtitle,2);var time=new FlowLayoutPanel{FlowDirection=FlowDirection.TopDown,AutoSize=true};time.Controls.Add(new Label{Text="THỜI GIAN CÒN LẠI",Font=new Font("Segoe UI",12,FontStyle.Bold),AutoSize=true});time.Controls.Add(countdown);root.Controls.Add(time,0,2);var cards=new TableLayoutPanel{AutoSize=true,ColumnCount=2};cards.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));cards.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));foreach(var item in new[]{("Đã dùng hôm nay","Used"),("Hạn mức hôm nay","Quota"),("Thời gian được cộng","Grants"),("Trạng thái","State")})AddField(cards,item.Item1,item.Item2,overview);root.Controls.Add(cards,1,2);var actions=new FlowLayoutPanel{Dock=DockStyle.Bottom,AutoSize=true,Padding=new Padding(0,22,0,0)};AddButton(actions,"+15 phút",()=>RunAsync(ParentControlAction.GrantMinutes,15));AddButton(actions,"+30 phút",()=>RunAsync(ParentControlAction.GrantMinutes,30));AddButton(actions,"+60 phút",()=>RunAsync(ParentControlAction.GrantMinutes,60));AddButton(actions,"Cộng tùy chọn",CustomGrantAsync);AddButton(actions,"Khóa",()=>RunAsync(ParentControlAction.SetParentLock));AddButton(actions,"Bỏ khóa",()=>RunAsync(ParentControlAction.ClearParentLock));AddButton(actions,"Override",()=>RunAsync(ParentControlAction.EmergencyOverride));reset=AddButton(actions,"Đặt lại dữ liệu thử nghiệm M1",()=>RunAsync(ParentControlAction.ResetM1));reset.Visible=false;root.Controls.Add(actions,0,3);root.SetColumnSpan(actions,2);tab.Controls.Add(root);return tab;}
 private TabPage AppTab(){var tab=new TabPage("ỨNG DỤNG");apps=new AppPolicyPanel(controller);apps.RefreshRequested+=async(_,_)=>await RefreshAppsAsync();tab.Controls.Add(apps);return tab;}
 private TabPage DiagnosticsTab(){var tab=new TabPage("CHẨN ĐOÁN M1");var root=new TableLayoutPanel{Dock=DockStyle.Fill,AutoScroll=true,Padding=new Padding(22),ColumnCount=2};root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,38));root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,62));foreach(var item in new[]{("Hồ sơ","Profile"),("Phiên Windows","Session"),("Chế độ an toàn","TestMode"),("SessionAgent","Agent"),("Hoạt động","Activity"),("Nguồn hoạt động","ActivitySource"),("Nhàn rỗi thiết bị","Idle"),("Nhàn rỗi Windows","WindowsIdle"),("Tuổi mẫu","SampleAge"),("Phiên theo dõi","TrackedSession"),("Đã ghi hôm nay","RecordedSeconds"),("Lần ghi cuối","Checkpoint"),("Khóa rõ ràng","LockLatch"),("WTS kết nối","WtsConnection"),("WTS SessionFlags","WtsFlags"),("Thông báo phiên","Notifications"),("Lỗi thông báo","NotificationError"),("Ngưỡng nhàn rỗi","IdleThreshold"),("Quét ứng dụng lần cuối","AppScanAt"),("Process đã xem","AppProcesses"),("Ứng dụng người dùng","AppUsers"),("Ứng dụng nền","AppBackground"),("Hệ thống được bảo vệ","AppSystem"),("Lỗi quét ứng dụng","AppError")})AddField(root,item.Item1,item.Item2,diagnostics);tab.Controls.Add(root);return tab;}
 private static void AddField(TableLayoutPanel panel,string label,string key,Dictionary<string,Label> bag){var row=panel.RowCount++;panel.RowStyles.Add(new RowStyle(SizeType.AutoSize));var value=new Label{Text="—",AutoSize=true,Padding=new Padding(4),Font=new Font("Segoe UI",10,FontStyle.Bold)};bag[key]=value;panel.Controls.Add(new Label{Text=label,AutoSize=true,Padding=new Padding(4)},0,row);panel.Controls.Add(value,1,row);}
 private static Button AddButton(FlowLayoutPanel panel,string text,Func<Task> action){var b=new Button{Text=text,AutoSize=true,MinimumSize=new Size(120,42),Margin=new Padding(5)};b.Click+=async(_,_)=>await action();panel.Controls.Add(b);return b;}
 public static string FormatCountdown(double seconds){var total=Math.Max(0,(long)Math.Floor(seconds));return $"{total/3600:D2}:{total%3600/60:D2}:{total%60:D2}";}
 private async Task CustomGrantAsync(){using var dialog=new Form{Text="Cộng phút tùy chọn",StartPosition=FormStartPosition.CenterParent,Size=new Size(330,155)};var input=new NumericUpDown{Minimum=1,Maximum=1440,Value=15,Location=new Point(20,25),Width=130};var ok=new Button{Text="Cộng phút",DialogResult=DialogResult.OK,Location=new Point(170,22)};dialog.Controls.AddRange([new Label{Text="Số phút:",Location=new Point(20,5),AutoSize=true},input,ok]);if(dialog.ShowDialog(this)==DialogResult.OK)await RunAsync(ParentControlAction.GrantMinutes,(int)input.Value);}
 private async Task RunAsync(ParentControlAction action,int? minutes=null)=>await DisplayAsync(await controller.SendAsync(action,minutes));
 private async Task RefreshAppsAsync(){if(refreshing)return;refreshing=true;try{await DisplayAsync(await controller.RefreshAppsAsync());}finally{refreshing=false;}}
 private async Task RefreshAsync(){if(refreshing)return;refreshing=true;try{await DisplayAsync(await controller.RefreshAsync());}finally{refreshing=false;}}
 private Task DisplayAsync(ParentUiResult result){message.Text=result.Message;message.ForeColor=result.Success?Color.DarkGreen:Color.Firebrick;if(result.Status is not { } s)return Task.CompletedTask;countdown.Text=FormatCountdown(s.RemainingSeconds);overview["Used"].Text=$"{s.UsedMinutes} phút";overview["Quota"].Text=$"{s.QuotaMinutes} phút";overview["Grants"].Text=$"{s.GrantMinutes} phút";overview["State"].Text=s.State;apps?.Update(s.Apps);diagnostics["Profile"].Text=s.ProfileId;diagnostics["Session"].Text=s.ManagedSessionId.ToString(CultureInfo.CurrentCulture);diagnostics["TestMode"].Text=s.TestMode?"BẬT (không khóa thật)":"TẮT";if(s.Diagnostics is { } d){diagnostics["Agent"].Text=d.SessionAgentConnected?"KẾT NỐI":"MẤT KẾT NỐI";diagnostics["Activity"].Text=d.ActivityState;diagnostics["ActivitySource"].Text=d.ActivitySource;diagnostics["Idle"].Text=d.IdleSeconds is { } i?$"{i:F1} giây":"—";diagnostics["WindowsIdle"].Text=d.WindowsIdleSeconds is { } wi?$"{wi:F1} giây":"—";diagnostics["SampleAge"].Text=d.SampleAgeSeconds is { } a?$"{a:F1} giây":"—";diagnostics["TrackedSession"].Text=d.TrackedSessionId.ToString(CultureInfo.CurrentCulture);diagnostics["RecordedSeconds"].Text=$"{d.RecordedTodaySeconds:F1} giây";diagnostics["Checkpoint"].Text=d.LastCheckpointAtUtc?.ToLocalTime().ToString("HH:mm:ss",CultureInfo.CurrentCulture)??"—";diagnostics["LockLatch"].Text=d.ExplicitLockLatched?"LOCKED":"UNLOCKED";diagnostics["WtsConnection"].Text=d.WtsConnectionState?.ToString(CultureInfo.CurrentCulture)??"—";diagnostics["WtsFlags"].Text=d.WtsSessionFlags?.ToString(CultureInfo.CurrentCulture)??"—";diagnostics["Notifications"].Text=d.SessionNotificationsAvailable?"AVAILABLE":"DEGRADED";diagnostics["NotificationError"].Text=d.NotificationError??"—";diagnostics["IdleThreshold"].Text=$"{d.IdleThresholdMinutes} phút";}if(s.Apps?.Discovery is { } scan){diagnostics["AppScanAt"].Text=scan.LastScanAtUtc?.ToLocalTime().ToString("HH:mm:ss",CultureInfo.CurrentCulture)??"—";diagnostics["AppProcesses"].Text=scan.ProcessesExamined.ToString(CultureInfo.CurrentCulture);diagnostics["AppUsers"].Text=scan.UserApplications.ToString(CultureInfo.CurrentCulture);diagnostics["AppBackground"].Text=scan.BackgroundHelpers.ToString(CultureInfo.CurrentCulture);diagnostics["AppSystem"].Text=scan.SystemProtected.ToString(CultureInfo.CurrentCulture);diagnostics["AppError"].Text=scan.DiscoveryError??"—";}if(reset is not null)reset.Visible=s.TestMode&&s.ProfileId=="m1-child";return Task.CompletedTask;}
}