using TuoiTho.Core.Policy;
namespace TuoiTho.Parent;
public sealed class WebPolicyPanel : UserControl
{
 private readonly ParentDesktopController controller; private readonly TextBox youtube=new(){Width=300,PlaceholderText="Dán URL kênh hoặc @handle"};private readonly TextBox tiktok=new(){Width=300,PlaceholderText="Dán URL hoặc @username"};private readonly DataGridView grid=new(){Dock=DockStyle.Fill,AutoGenerateColumns=false,ReadOnly=true,AllowUserToAddRows=false,RowHeadersVisible=false};private readonly Label message=new(){AutoSize=true}; private IReadOnlyList<WebRule> rules=[];
 public WebPolicyPanel(ParentDesktopController controller){this.controller=controller;Dock=DockStyle.Fill;var root=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(20),RowCount=4};root.RowStyles.Add(new RowStyle(SizeType.AutoSize));root.RowStyles.Add(new RowStyle(SizeType.AutoSize));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));root.RowStyles.Add(new RowStyle(SizeType.AutoSize));root.Controls.Add(new Label{Text="WEB",Font=new Font("Segoe UI",16,FontStyle.Bold),AutoSize=true},0,0);var actions=new FlowLayoutPanel{AutoSize=true};Add(actions,"Cho phép YouTube",()=>SetSite(BrowserProvider.YouTube,WebRuleDecision.Allow));Add(actions,"Chặn YouTube",()=>SetSite(BrowserProvider.YouTube,WebRuleDecision.Block));actions.Controls.Add(youtube);Add(actions,"Cho phép kênh",()=>Channel(WebRuleDecision.Allow));Add(actions,"Chặn kênh",()=>Channel(WebRuleDecision.Block));Add(actions,"Cho phép TikTok",()=>SetSite(BrowserProvider.TikTok,WebRuleDecision.Allow));Add(actions,"Chặn TikTok",()=>SetSite(BrowserProvider.TikTok,WebRuleDecision.Block));actions.Controls.Add(tiktok);Add(actions,"Cho phép tài khoản",()=>Creator(WebRuleDecision.Allow));Add(actions,"Chặn tài khoản",()=>Creator(WebRuleDecision.Block));Add(actions,"Xóa quy tắc",Delete);root.Controls.Add(actions,0,1);grid.Columns.Add("Provider","Nền tảng");grid.Columns.Add("Label","Kênh / tài khoản");grid.Columns.Add("Decision","Quy tắc");root.Controls.Add(grid,0,2);root.Controls.Add(message,0,3);Controls.Add(root);}
 public void Update(ParentWebControlStatus? status){rules=status?.Rules??[];grid.Rows.Clear();foreach(var rule in rules)grid.Rows.Add(rule.Provider==BrowserProvider.YouTube?"YouTube":"TikTok",rule.DisplayLabel,rule.Decision==WebRuleDecision.Allow?"CHO PHÉP":"CHẶN");}
 private static Button Add(FlowLayoutPanel p,string t,Func<Task> a){var b=new Button{Text=t,AutoSize=true};b.Click+=async(_,_)=>await a();p.Controls.Add(b);return b;}
 private Task SetSite(BrowserProvider p,WebRuleDecision d)=>Send(ParentControlAction.SaveWebRule,new("m1-child",p,WebRuleScope.Site,d,WebPolicyEngine.SiteKey(p),p==BrowserProvider.YouTube?"YouTube":"TikTok"));
 private Task Channel(WebRuleDecision d){if(!WebIdentityNormalizer.TryNormalizeYouTubeChannel(youtube.Text,out var key,out var label)){message.Text="URL hoặc @handle YouTube không hợp lệ.";return Task.CompletedTask;}return Send(ParentControlAction.SaveWebRule,new("m1-child",BrowserProvider.YouTube,WebRuleScope.YouTubeChannel,d,key,label));}
 private Task Creator(WebRuleDecision d){if(!WebIdentityNormalizer.TryNormalizeTikTokCreator(tiktok.Text,out var key,out var label)){message.Text="URL hoặc @username TikTok không hợp lệ.";return Task.CompletedTask;}return Send(ParentControlAction.SaveWebRule,new("m1-child",BrowserProvider.TikTok,WebRuleScope.TikTokCreator,d,key,label));}
 private Task Delete(){if(grid.CurrentRow?.Index is not int index||index<0||index>=rules.Count)return Task.CompletedTask;return Send(ParentControlAction.RemoveWebRule,rules[index]);}
 private async Task Send(ParentControlAction action,WebRule rule){var result=await controller.SendWebRuleAsync(action,rule);message.Text=result.Message;Update(result.Status?.Web);}
}