using System.Reflection;
using TuoiTho.Core.Policy;
using TuoiTho.Storage;
namespace TuoiTho.Tests;
public sealed class AppPolicyTests
{
 [Fact] public void ExplicitRulesAndDefaultsHaveDeterministicPrecedence(){var app=AppIdentity.FromExecutablePath("C:\\Apps\\Chess.exe","Chess");var other=AppIdentity.FromExecutablePath("C:\\Apps\\Other.exe","Chess");var rules=new[]{new AppRule("child",app,AppRuleDecision.Allow),new AppRule("child",app,AppRuleDecision.Block)};Assert.Equal(AppSimulationDecision.WouldBlock,AppPolicyEngine.Evaluate(app,rules,DefaultAppPolicy.AllowUnknown).Decision);Assert.Equal(AppSimulationDecision.WouldAllow,AppPolicyEngine.Evaluate(app,[new AppRule("child",app,AppRuleDecision.Allow)],DefaultAppPolicy.BlockUnknown).Decision);Assert.Equal(AppSimulationDecision.BlockUnknown,AppPolicyEngine.Evaluate(other,[],DefaultAppPolicy.BlockUnknown).Decision);Assert.Equal(AppSimulationDecision.WouldAllow,AppPolicyEngine.Evaluate(other,[],DefaultAppPolicy.AllowUnknown).Decision);}
 [Fact] public async Task RulesDefaultsAndObservationsPersistAcrossReopenAndAreSessionScoped(){var path=Path.Combine(Path.GetTempPath(),$"tuoitho-app-{Guid.NewGuid():N}.db");try{var app=AppIdentity.FromExecutablePath("C:\\Apps\\Notepad.exe","Renamed text");var db=new SqliteDatabase(path);await db.InitializeAsync();var store=new SqliteAppPolicyStore(db);await store.SetDefaultPolicyAsync("child",DefaultAppPolicy.BlockUnknown);await store.SaveRuleAsync(new("child",app,AppRuleDecision.Allow));var now=DateTimeOffset.UtcNow;await store.RecordObservationAsync(new("child",7,app,now,now));var reopened=new SqliteAppPolicyStore(new SqliteDatabase(path));Assert.Equal(DefaultAppPolicy.BlockUnknown,await reopened.GetDefaultPolicyAsync("child"));Assert.Equal(AppRuleDecision.Allow,Assert.Single(await reopened.GetRulesAsync("child")).Decision);Assert.Single(await reopened.GetObservedAppsAsync("child",7));Assert.Empty(await reopened.GetObservedAppsAsync("child",8));}finally{if(File.Exists(path))File.Delete(path);}}
 [Fact] public void StoredObservationModelContainsNoContentOrSurveillanceFields(){var names=typeof(ObservedApp).GetProperties(BindingFlags.Public|BindingFlags.Instance).Select(p=>p.Name);Assert.DoesNotContain(names,n=>n.Contains("Command",StringComparison.OrdinalIgnoreCase)||n.Contains("Window",StringComparison.OrdinalIgnoreCase)||n.Contains("Url",StringComparison.OrdinalIgnoreCase)||n.Contains("Document",StringComparison.OrdinalIgnoreCase)||n.Contains("Screen",StringComparison.OrdinalIgnoreCase));}
}