using Microsoft.Extensions.Logging.Abstractions;
using TuoiTho.Core.Policy;
using TuoiTho.Core.Time;
using TuoiTho.Service;
namespace TuoiTho.Tests;
public sealed class M1TestModeSystemCheckTests
{
 [Fact] public async Task SystemCheckM1TestModeWarningSimulatedLockThenGrantAllows(){var clock=new FakeClock(new DateTimeOffset(2026,9,14,9,0,0,TimeSpan.Zero),TimeZoneInfo.Utc);var policy=new DeviceTimePolicy("child",7,30,[new AllowedUsageWindow(DayOfWeek.Monday,new(9,0),new(10,0))],DeviceTimePolicy.DefaultWarnings,false,false,true){ManagedUserSid="child"};var store=new Store(policy);var usage=new FakeTimeUsageStore();await usage.SaveAsync("child",new TimeTrackingCheckpoint(7,SessionActivityState.Active,clock.UtcNow,clock.UtcNow),[new DailyUsageSlice(new DateOnly(2026,9,14),TimeSpan.FromMinutes(30))]);var native=new Native();var publisher=new Publisher();var signal=new PolicyChangeSignal();var coordinator=new DevicePolicyCoordinator(store,usage,clock,new DeviceTimePolicyEngine(clock),new SafeChildSessionEnforcer(native,NullLogger<SafeChildSessionEnforcer>.Instance),publisher,signal);Assert.Equal("SIMULATED_LOCK",(await coordinator.EvaluateAsync("child"))!.Outcome);var parent=new ParentControlService(store,clock,signal);Assert.True((await parent.ExecuteAsync(new(ParentControlAction.GrantMinutes,"child",7,15),"parent",new HashSet<string>{"parent"})).Accepted);Assert.Equal("ALLOWED",(await coordinator.EvaluateAsync("child"))!.Outcome);Assert.Empty(native.Disconnected);Assert.Equal(AccessDenyReason.None,publisher.Last!.Reason);}
 private sealed class Store(DeviceTimePolicy p):IDeviceTimePolicyStore{private readonly List<TemporaryGrant> grants=[];public Task<DeviceTimePolicy?> LoadAsync(string id,CancellationToken c=default)=>Task.FromResult<DeviceTimePolicy?>(p);public Task SaveAsync(DeviceTimePolicy value,CancellationToken c=default){p=value;return Task.CompletedTask;}public Task AddGrantAsync(string id,TemporaryGrant g,CancellationToken c=default){grants.Add(g);return Task.CompletedTask;}public Task<IReadOnlyList<TemporaryGrant>> GetGrantsAsync(string id,CancellationToken c=default)=>Task.FromResult<IReadOnlyList<TemporaryGrant>>(grants);}
 private sealed class Publisher:IPolicyWarningPublisher{public SessionWarning? Last;public Task PublishAsync(SessionWarning w,CancellationToken c=default){Last=w;return Task.CompletedTask;}}
 private sealed class Native:IManagedSessionNativeApi{public List<int> Disconnected=[];public Task<bool> IsManagedChildSessionAsync(int i,string s,CancellationToken c=default)=>Task.FromResult(true);public Task DisconnectSessionAsync(int i,CancellationToken c=default){Disconnected.Add(i);return Task.CompletedTask;}}
}