using System.IO.Pipes;using System.Text.Json;using Microsoft.Extensions.Logging.Abstractions;using Microsoft.Extensions.Options;using TuoiTho.Core.Policy;using TuoiTho.Core.Time;using TuoiTho.Parent;using TuoiTho.Service;using TuoiTho.Storage;
namespace TuoiTho.Tests;
public sealed class M1TesterPackageTests
{
 [Fact] public async Task ParentClientReceivesAcceptedResponse(){var name=$"TuoiTho.Parent.Test.{Guid.NewGuid():N}";var server=Task.Run(async()=>{using var pipe=new NamedPipeServerStream(name,PipeDirection.InOut,1,PipeTransmissionMode.Byte,PipeOptions.Asynchronous);await pipe.WaitForConnectionAsync();using var reader=new StreamReader(pipe,leaveOpen:true);var command=JsonSerializer.Deserialize<ParentControlCommand>((await reader.ReadLineAsync())!);Assert.Equal(ParentControlAction.GetStatus,command!.Action);using var writer=new StreamWriter(pipe,leaveOpen:true){AutoFlush=true};await writer.WriteLineAsync(JsonSerializer.Serialize(new ParentControlResult(true,null,null,new ParentControlStatus("p",7,true,1,3,0,2,"ALLOWED"))));});var result=await new LocalParentControlClient(name).SendAsync(new(ParentControlAction.GetStatus,"p",7));await server;Assert.True(result.Accepted);Assert.Equal("ALLOWED",result.Status!.State);}
 [Fact] public async Task StatusAndUnauthorizedAreReported(){var clock=new FakeClock(new DateTimeOffset(2026,9,14,9,0,0,TimeSpan.Zero),TimeZoneInfo.Utc);var policy=Policy();var store=new Store(policy);var service=new ParentControlService(store,new FakeTimeUsageStore(),clock,new DeviceTimePolicyEngine(clock),new PolicyChangeSignal());var rejected=await service.ExecuteAsync(new(ParentControlAction.GetStatus,"child",7),"child",new HashSet<string>{"parent"});Assert.False(rejected.Accepted);var accepted=await service.ExecuteAsync(new(ParentControlAction.GetStatus,"child",7),"parent",new HashSet<string>{"parent"});Assert.True(accepted.Accepted);Assert.True(accepted.Status!.TestMode);Assert.Equal("ALLOWED",accepted.Status.State);}
 [Fact] public async Task BootstrapForcesTestModeAndCurrentSession(){var path=Path.Combine(Path.GetTempPath(),$"m1-{Guid.NewGuid():N}.db");try{var db=new SqliteDatabase(path);var store=new SqliteDeviceTimePolicyStore(db);var options=Options.Create(new M1BootstrapOptions{Enabled=true,ProfileId="m1",ManagedSessionId=7,ManagedUserSid="S-1-5-21-test",QuotaMinutes=3});var boot=new M1Bootstrapper(db,store,options,new PolicyChangeSignal());await boot.StartAsync(CancellationToken.None);var policy=(await store.LoadAsync("m1"))!;Assert.True(policy.TestMode);Assert.Equal(7,policy.ManagedSessionId);Assert.Equal("S-1-5-21-test",policy.ManagedUserSid);Assert.Equal(3,policy.DailyQuotaMinutes);}finally{if(File.Exists(path))File.Delete(path);}}
 [Fact] public void StopScriptCannotEnforce(){var text=File.ReadAllText(Path.Combine(AppContext.BaseDirectory,"..","..","..","..","..","scripts","M1-STOP.ps1"));Assert.DoesNotContain("WTSDisconnect",text);Assert.DoesNotContain("shutdown",text,StringComparison.OrdinalIgnoreCase);Assert.Contains("TestMode",text);}
 private static DeviceTimePolicy Policy()=>new("child",7,3,[new AllowedUsageWindow(DayOfWeek.Monday,new(0,0),new(23,59))],DeviceTimePolicy.DefaultWarnings,false,false,true){ManagedUserSid="S-1-5-21-child"};
 private sealed class Store(DeviceTimePolicy p):IDeviceTimePolicyStore{public Task<DeviceTimePolicy?> LoadAsync(string id,CancellationToken c=default)=>Task.FromResult<DeviceTimePolicy?>(p);public Task SaveAsync(DeviceTimePolicy p,CancellationToken c=default)=>Task.CompletedTask;public Task AddGrantAsync(string id,TemporaryGrant g,CancellationToken c=default)=>Task.CompletedTask;public Task<IReadOnlyList<TemporaryGrant>> GetGrantsAsync(string id,CancellationToken c=default)=>Task.FromResult<IReadOnlyList<TemporaryGrant>>([]);}
}