using TuoiTho.Core.Policy;
using TuoiTho.Core.Time;
using TuoiTho.Service;
namespace TuoiTho.Tests;
public sealed class RefreshAppsTests
{
 [Fact] public void ForeignSessionIsExcludedByDiscoveryFilter(){Assert.True(WindowsManagedSessionAppDiscovery.IsManagedSession(7,7));Assert.False(WindowsManagedSessionAppDiscovery.IsManagedSession(8,7));Assert.Equal(AppClassification.SystemProtected,WindowsManagedSessionAppDiscovery.Classify("C:\\Apps\\Note.exe",8,7,true));}
 [Fact] public void VisibleManagedAppIsAUserApplicationAndWindowsInfrastructureIsProtected(){Assert.Equal(AppClassification.UserApplication,WindowsManagedSessionAppDiscovery.Classify("C:\\Apps\\Notepad.exe",7,7,true));Assert.Equal(AppClassification.UserApplication,WindowsManagedSessionAppDiscovery.Classify("C:\\WindowsApps\\CalculatorApp.exe",7,7,false));Assert.Equal(AppClassification.SystemProtected,WindowsManagedSessionAppDiscovery.Classify("C:\\Windows\\System32\\svchost.exe",7,7,true));Assert.Equal(AppClassification.BackgroundHelper,WindowsManagedSessionAppDiscovery.Classify("C:\\Apps\\AudioHelper.exe",7,7,false));}
 [Fact] public void ControlPlaneAndWindowsSystemAppsAreNeverControllable(){const string install="C:\\Program Files\\TuoiTho";foreach(var executable in new[]{"TuoiTho.Parent.exe","TuoiTho.Service.exe","TuoiTho.SessionAgent.exe","RecoveryTool.exe"})Assert.Equal(AppClassification.SystemProtected,WindowsManagedSessionAppDiscovery.Classify(Path.Combine(install,executable),7,7,true,install));Assert.Equal(AppClassification.SystemProtected,WindowsManagedSessionAppDiscovery.Classify("C:\\Windows\\SystemApps\\ShellExperienceHost.exe",7,7,true));Assert.Equal(AppClassification.UserApplication,WindowsManagedSessionAppDiscovery.Classify("C:\\Program Files\\Google\\Chrome\\chrome.exe",7,7,true));Assert.Equal(AppClassification.UserApplication,WindowsManagedSessionAppDiscovery.Classify("C:\\Windows\\System32\\notepad.exe",7,7,true));Assert.Equal(AppClassification.UserApplication,WindowsManagedSessionAppDiscovery.Classify("C:\\WindowsApps\\CalculatorApp.exe",7,7,false));Assert.Equal(AppClassification.UserApplication,WindowsManagedSessionAppDiscovery.Classify("C:\\Program Files\\Zalo\\Zalo.exe",7,7,true));}
 [Fact] public async Task RefreshAppsDiscoversPersistsAndReturnsSameResponse(){var app=AppIdentity.FromExecutablePath("C:\\Apps\\Notepad.exe","Notepad");var discovery=new FakeDiscovery(new(DateTimeOffset.UtcNow,4,1,1,null,[new DiscoveredApplication(app,AppClassification.UserApplication)],1,0,0));var apps=new MemoryApps();var policy=new DeviceTimePolicy("child",7,30,[],DeviceTimePolicy.DefaultWarnings,false,false,true);var result=await Create(policy,apps,discovery).ExecuteAsync(new(ParentControlAction.RefreshApps,"child",7),"parent",new HashSet<string>{"parent"});Assert.True(result.Accepted);Assert.Equal(1,discovery.Calls);Assert.Equal(AppClassification.UserApplication,Assert.Single(result.Status!.Apps!.ObservedApps).Classification);Assert.Equal(4,result.Status.Apps.Discovery!.ProcessesExamined);}
 [Fact] public async Task GetStatusDoesNotTriggerDiscovery(){var discovery=new FakeDiscovery(new(DateTimeOffset.UtcNow,0,0,0,null,[]));var result=await Create(new DeviceTimePolicy("child",7,30,[],DeviceTimePolicy.DefaultWarnings,false,false,true),new MemoryApps(),discovery).ExecuteAsync(new(ParentControlAction.GetStatus,"child",7),"parent",new HashSet<string>{"parent"});Assert.True(result.Accepted);Assert.Equal(0,discovery.Calls);}
 [Fact] public async Task DiscoveryErrorIsReturnedForM1Diagnostics(){var discovery=new FakeDiscovery(new(DateTimeOffset.UtcNow,0,0,0,"Access denied",[]));var result=await Create(new DeviceTimePolicy("child",7,30,[],DeviceTimePolicy.DefaultWarnings,false,false,true),new MemoryApps(),discovery).ExecuteAsync(new(ParentControlAction.RefreshApps,"child",7),"parent",new HashSet<string>{"parent"});Assert.False(result.Accepted);Assert.Equal("Access denied",result.Status!.Apps!.Discovery!.DiscoveryError);}
 static ParentControlService Create(DeviceTimePolicy p,MemoryApps apps,FakeDiscovery discovery)=>new(new MemoryPolicy(p),new ZeroUsage(),new FakeClock(DateTimeOffset.UtcNow,TimeZoneInfo.Utc),new DeviceTimePolicyEngine(new FakeClock(DateTimeOffset.UtcNow,TimeZoneInfo.Utc)),new PolicyChangeSignal(),appPolicies:apps,appPolicyEngine:new AppPolicyEngine(),appDiscovery:discovery);
 sealed class FakeDiscovery(AppDiscoveryResult result):IManagedSessionAppDiscovery{public int Calls;public AppDiscoveryResult Discover(int sessionId){Calls++;return result;}}
 sealed class MemoryPolicy(DeviceTimePolicy policy):IDeviceTimePolicyStore{public Task<DeviceTimePolicy?> LoadAsync(string id,CancellationToken t=default)=>Task.FromResult<DeviceTimePolicy?>(policy);public Task SaveAsync(DeviceTimePolicy p,CancellationToken t=default)=>Task.CompletedTask;public Task AddGrantAsync(string p,TemporaryGrant g,CancellationToken t=default)=>Task.CompletedTask;public Task ClearGrantsAsync(string p,CancellationToken t=default)=>Task.CompletedTask;public Task<IReadOnlyList<TemporaryGrant>> GetGrantsAsync(string p,CancellationToken t=default)=>Task.FromResult<IReadOnlyList<TemporaryGrant>>([]);}
 sealed class ZeroUsage:ITimeUsageStore{public Task<TimeTrackingCheckpoint?> LoadCheckpointAsync(string p,CancellationToken t=default)=>Task.FromResult<TimeTrackingCheckpoint?>(null);public Task SaveAsync(string p,TimeTrackingCheckpoint c,IReadOnlyList<DailyUsageSlice> s,CancellationToken t=default)=>Task.CompletedTask;public Task ResetUsageAsync(string p,DateOnly d,CancellationToken t=default)=>Task.CompletedTask;public Task<TimeSpan> GetUsageAsync(string p,DateOnly d,CancellationToken t=default)=>Task.FromResult(TimeSpan.Zero);}
 sealed class MemoryApps:IAppPolicyStore{readonly List<ObservedApp> list=[];public Task<DefaultAppPolicy> GetDefaultPolicyAsync(string p,CancellationToken t=default)=>Task.FromResult(DefaultAppPolicy.BlockUnknown);public Task SetDefaultPolicyAsync(string p,DefaultAppPolicy d,CancellationToken t=default)=>Task.CompletedTask;public Task<IReadOnlyList<AppRule>> GetRulesAsync(string p,CancellationToken t=default)=>Task.FromResult<IReadOnlyList<AppRule>>([]);public Task SaveRuleAsync(AppRule r,CancellationToken t=default)=>Task.CompletedTask;public Task RemoveRuleAsync(string p,AppIdentity i,CancellationToken t=default)=>Task.CompletedTask;public Task<IReadOnlyList<ObservedApp>> GetObservedAppsAsync(string p,int s,CancellationToken t=default)=>Task.FromResult<IReadOnlyList<ObservedApp>>(list);public Task RecordObservationAsync(ObservedApp o,CancellationToken t=default){list.Add(o);return Task.CompletedTask;}}
}